# GApps dependencies
PRODUCT_COPY_FILES += \
    vendor/google/proprietary/system/lib/librs.fixedframe.so:system/lib/librs.fixedframe.so \
    vendor/google/proprietary/system/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/google/proprietary/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/google/proprietary/system/lib/libgtalk_stabilize.so:system/lib/libgtalk_stabilize.so \
    vendor/google/proprietary/system/lib/libwebp_android.so:system/lib/libwebp_android.so \
    vendor/google/proprietary/system/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so \
    vendor/google/proprietary/system/lib/librs.retrolux.so:system/lib/librs.retrolux.so \
    vendor/google/proprietary/system/lib/libgoogle_recognizer_jni.so:system/lib/libgoogle_recognizer_jni.so \
    vendor/google/proprietary/system/lib/librsjni.so:system/lib/librsjni.so \
    vendor/google/proprietary/system/lib/libjni_t13n_shared_engine.so:system/lib/libjni_t13n_shared_engine.so \
    vendor/google/proprietary/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    vendor/google/proprietary/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    vendor/google/proprietary/system/lib/librs.drama.so:system/lib/librs.drama.so \
    vendor/google/proprietary/system/lib/libgoggles_clientvision.so:system/lib/libgoggles_clientvision.so \
    vendor/google/proprietary/system/lib/librs.grey.so:system/lib/librs.grey.so \
    vendor/google/proprietary/system/lib/libgtalk_jni.so:system/lib/libgtalk_jni.so \
    vendor/google/proprietary/system/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
    vendor/google/proprietary/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/google/proprietary/system/lib/librs.antblur_drama.so:system/lib/librs.antblur_drama.so \
    vendor/google/proprietary/system/lib/libRSSupport.so:system/lib/libRSSupport.so \
    vendor/google/proprietary/system/lib/librs.film_base.so:system/lib/librs.film_base.so \
    vendor/google/proprietary/system/lib/librs.image_wrapper.so:system/lib/librs.image_wrapper.so \
    vendor/google/proprietary/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/google/proprietary/system/lib/libwebrtc_audio_coding.so:system/lib/libwebrtc_audio_coding.so \
    vendor/google/proprietary/system/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    vendor/google/proprietary/system/lib/librs.antblur.so:system/lib/librs.antblur.so \
    vendor/google/proprietary/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    vendor/google/proprietary/system/lib/librs.antblur_constant.so:system/lib/librs.antblur_constant.so \
    vendor/google/proprietary/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    vendor/google/proprietary/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/google/proprietary/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/google/proprietary/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/google/proprietary/system/tts/lang_pico/it-IT_ta.bin:system/tts/lang_pico/it-IT_ta.bin \
    vendor/google/proprietary/system/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
    vendor/google/proprietary/system/tts/lang_pico/it-IT_cm0_sg.bin:system/tts/lang_pico/it-IT_cm0_sg.bin \
    vendor/google/proprietary/system/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin \
    vendor/google/proprietary/system/tts/lang_pico/de-DE_ta.bin:system/tts/lang_pico/de-DE_ta.bin \
    vendor/google/proprietary/system/tts/lang_pico/fr-FR_ta.bin:system/tts/lang_pico/fr-FR_ta.bin \
    vendor/google/proprietary/system/tts/lang_pico/fr-FR_nk0_sg.bin:system/tts/lang_pico/fr-FR_nk0_sg.bin \
    vendor/google/proprietary/system/tts/lang_pico/de-DE_gl0_sg.bin:system/tts/lang_pico/de-DE_gl0_sg.bin \
    vendor/google/proprietary/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    vendor/google/proprietary/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/google/proprietary/system/usr/srec/en-US/google_hotword.config:system/usr/srec/en-US/google_hotword.config \
    vendor/google/proprietary/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    vendor/google/proprietary/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    vendor/google/proprietary/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/google/proprietary/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/google/proprietary/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    vendor/google/proprietary/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
    vendor/google/proprietary/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/google/proprietary/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
    vendor/google/proprietary/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/google/proprietary/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/google/proprietary/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/google/proprietary/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    vendor/google/proprietary/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
    vendor/google/proprietary/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/google/proprietary/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/google/proprietary/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    vendor/google/proprietary/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    vendor/google/proprietary/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
    vendor/google/proprietary/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/google/proprietary/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/google/proprietary/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \
    vendor/google/proprietary/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/google/proprietary/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    vendor/google/proprietary/system/usr/srec/en-US/classifier:system/usr/srec/en-US/classifier \
    vendor/google/proprietary/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/google/proprietary/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/google/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/google/proprietary/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/google/proprietary/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/google/proprietary/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/google/proprietary/system/etc/g.prop:system/etc/g.prop

PRODUCT_PACKAGES += \
    GoogleEars \
    GmsCore \
    VoiceSearchStub \
    GoogleTTS \
    SetupWizard \
    GoogleOneTimeInitializer \
    MediaUploader \
    GoogleFeedback \
    GoogleCalendarSyncAdapter \
    GoogleBackupTransport \
    GenieWidget \
    GoogleContactsSyncAdapter \
    NetworkLocation \
    LatinImeDictionaryPack \
    GoogleLoginService \
    GooglePartnerSetup \
    GooglePlus \
    TalkBack \
    Gmail \
    Phonesky \
    QuickSearchBoxGoogle \
    GoogleServicesFramework \
    ChromeBookmarksSyncAdapter \
    ConfigUpdater

# FaceLock build.prop
PRODUCT_PROPERTY_OVERRIDES += \
    ro.facelock.black_timeout=1250 \
    ro.facelock.det_timeout=1500 \
    ro.facelock.rec_timeout=2500 \
    ro.facelock.lively_timeout=2500 \
    ro.facelock.est_max_time=1000 \
    ro.facelock.use_intro_anim=true
